#!/bin/sh -ex

# Install or update dotter
dotter_dir="${HOME}/.cargo/bin"
dotter="${dotter_dir}/dotter"
dotter_tmp="${dotter_dir}/.dotter.tmp"

if ! [ -x "${dotter}" ]; then
  echo "installing dotter"
  mkdir -p "${dotter_dir}"
else
  echo "updating dotter"
fi
curl -sL https://github.com/SuperCuber/dotter/releases/latest/download/dotter -o "${dotter_tmp}"
chmod +x "${dotter_tmp}"
mv "${dotter_tmp}" "${dotter}"

exec "${dotter}" deploy
