#!/bin/bash -ex

function install {
  url="$1"
  dir="$2"
  ext="$3"
  arg="$4 $5"

  tmp="$(mktemp -d)"
  trap "rm -rf $tmp" EXIT

  curl -s -L "$url" -o "$tmp/archive"
  mkdir "$tmp/extract"
  (
    cd "$tmp/extract"
    "$ext" $arg ../archive
    mkdir -p "$dir/"
    rsync --delete -av ./ "$dir/"
  )
}

## Language package managers

### npm
mkdir -p ~/.local/n/bin
curl -L https://raw.githubusercontent.com/tj/n/master/bin/n -o ~/.local/n/bin/n
chmod +x ~/.local/n/bin/n
N_PREFIX=~/.local/n N_CACHE_PREFIX=~/.cache ~/.local/n/bin/n lts

## Command line utilities
cargo install --quiet fd-find
cargo install --quiet ripgrep

# Only necessary client-side
if [ "x$1" = "xclient" ]; then
  install https://github.com/ryanoasis/nerd-fonts/releases/download/2.2.0-RC/FiraCode.zip \
    ~/.local/share/fonts/nerd-fonts-fira-code unzip
  fc-cache -f
fi

install https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz \
  ~/.local/nvim-nightly tar --strip-components=1 -xvf

go install github.com/mattn/efm-langserver@latest

#
# Protobuf editor support
#
install https://github.com/bufbuild/buf/releases/download/v1.3.1/buf-Linux-x86_64.tar.gz \
  ~/.local/buf tar --strip-components=1 -xvf

#
# Shell editor support
#
PATH=~/.local/n/bin:$PATH npm install --global --no-progress --silent bash-language-server
go install mvdan.cc/sh/v3/cmd/shfmt@latest
#cabal update
#cabal install ShellCheck

#
# Lua editor support
#
install https://github.com/sumneko/lua-language-server/releases/download/2.6.7/lua-language-server-2.6.7-linux-x64.tar.gz \
  ~/.local/lua-language-server tar -xvf
cargo install --quiet stylua

#ln -s .dotter/$(hostname).toml .dotter/local.toml
cargo install --quiet dotter
