- hosts: all
  tasks:
    - name: Configure git
      ansible.builtin.import_role:
        name: git

    - name: Install and configure wezterm
      ansible.builtin.import_role:
        name: wezterm
      when: gui

#[nvim.files]
#"config/nvim" = "~/.config/nvim"
#
#[stylua.files]
#"config/stylua" = "~/.config/stylua"
#
#[zsh.files]
#"zshenv" = "~/.zshenv"
