- hosts: all
  tasks:
    - name: Configure git
      ansible.builtin.template:
        src: 'config/git/config.j2'
        dest: '~/.config/git/config'
        backup: true

    - name: Install and configure wezterm
      ansible.builtin.import_role:
        name: wezterm
      when: gui

#[nvim.files]
#"config/nvim" = "~/.config/nvim"
#
#[stylua.files]
#"config/stylua" = "~/.config/stylua"
#
#[zsh.files]
#"zshenv" = "~/.zshenv"
