#!/bin/sh -ex

# Install or update rustup
rustup_dir="${HOME}/.cargo/bin"
rustup="${rustup_dir}/rustup"

if ! [ -x "${rustup}" ]; then
  echo "installing rustup"
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path --component miri --component rust-analyzer --default-toolchain nightly
else
  echo "updating rustup"
  "${rustup}" self update
fi
source "${HOME}/.cargo/env"

# Install stable toolchain as well
rustup toolchain install stable
#rustup default nightly

# Install or update dotter
dotter_dir="${HOME}/.cargo/bin"
dotter="${dotter_dir}/dotter"

if ! [ -x "${dotter}" ]; then
  echo "installing dotter"
else
  echo "updating dotter"
fi

cargo install --quiet dotter

exec "${dotter}" deploy
