[alacritty.files]
"alacritty.yml" = "~/.config/alacritty/alacritty.yml"

[nvim.files]
"config/nvim" = "~/.config/nvim"

[stylua.files]
"config/stylua" = "~/.config/stylua"

[zsh.files]
"zshenv" = "~/.zshenv"
