[alacritty.files]
"alacritty.yml" = "~/.config/alacritty/alacritty.yml"

[gdb.files]
# xdg_config_home support was added in 2020
# auto-load path is the work path
"gdbinit" = "~/.gdbinit"

[git.files]
"config/git" = "~/.config/git"

[nvim.files]
"config/nvim" = "~/.config/nvim"

[stylua.files]
"config/stylua" = "~/.config/stylua"

[wezterm.files]
"config/wezterm" = "~/.config/wezterm"

[zsh.files]
"zshenv" = "~/.zshenv"
