[alacritty.files]
"alacritty.yml" = "~/.config/alacritty/alacritty.yml"

[gdb.files]
"config/gdb" = "~/.config/gdb"

[git.files]
"config/git" = "~/.config/git"

[nvim.files]
"config/nvim" = "~/.config/nvim"

[stylua.files]
"config/stylua" = "~/.config/stylua"

[zsh.files]
"zshenv" = "~/.zshenv"
